//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 07:59:17 AM CEST 
//


package ou.xjc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Dyrektor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dyrektor">
 *   &lt;complexContent>
 *     &lt;extension base="{}Pracownik">
 *       &lt;sequence>
 *         &lt;element name="dodatekSluzbowy" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="kartaSluzbowa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="limitKosztow" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dyrektor", propOrder = {
    "dodatekSluzbowy",
    "kartaSluzbowa",
    "limitKosztow"
})
public class Dyrektor
    extends Pracownik
{

    protected double dodatekSluzbowy;
    @XmlElement(required = true)
    protected String kartaSluzbowa;
    protected double limitKosztow;

    /**
     * Gets the value of the dodatekSluzbowy property.
     * 
     */
    public double getDodatekSluzbowy() {
        return dodatekSluzbowy;
    }

    /**
     * Sets the value of the dodatekSluzbowy property.
     * 
     */
    public void setDodatekSluzbowy(double value) {
        this.dodatekSluzbowy = value;
    }

    /**
     * Gets the value of the kartaSluzbowa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKartaSluzbowa() {
        return kartaSluzbowa;
    }

    /**
     * Sets the value of the kartaSluzbowa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKartaSluzbowa(String value) {
        this.kartaSluzbowa = value;
    }

    /**
     * Gets the value of the limitKosztow property.
     * 
     */
    public double getLimitKosztow() {
        return limitKosztow;
    }

    /**
     * Sets the value of the limitKosztow property.
     * 
     */
    public void setLimitKosztow(double value) {
        this.limitKosztow = value;
    }

}
