//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 07:59:17 AM CEST 
//


package ou.xjc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Handlowiec complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Handlowiec">
 *   &lt;complexContent>
 *     &lt;extension base="{}Pracownik">
 *       &lt;sequence>
 *         &lt;element name="prowizja" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="limitProwizji" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Handlowiec", propOrder = {
    "prowizja",
    "limitProwizji"
})
public class Handlowiec
    extends Pracownik
{

    protected double prowizja;
    protected double limitProwizji;

    /**
     * Gets the value of the prowizja property.
     * 
     */
    public double getProwizja() {
        return prowizja;
    }

    /**
     * Sets the value of the prowizja property.
     * 
     */
    public void setProwizja(double value) {
        this.prowizja = value;
    }

    /**
     * Gets the value of the limitProwizji property.
     * 
     */
    public double getLimitProwizji() {
        return limitProwizji;
    }

    /**
     * Sets the value of the limitProwizji property.
     * 
     */
    public void setLimitProwizji(double value) {
        this.limitProwizji = value;
    }

}
