//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 07:59:17 AM CEST 
//


package ou.xjc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Pracownik complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Pracownik">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pesel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="imie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nazwisko" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stanowisko" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wynagrodzenie" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="telefon" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pracownik", propOrder = {
    "pesel",
    "imie",
    "nazwisko",
    "stanowisko",
    "wynagrodzenie",
    "telefon"
})
@XmlSeeAlso({
    Handlowiec.class,
    Dyrektor.class
})
public class Pracownik {

    @XmlElement(required = true)
    protected String pesel;
    @XmlElement(required = true)
    protected String imie;
    @XmlElement(required = true)
    protected String nazwisko;
    @XmlElement(required = true)
    protected String stanowisko;
    protected double wynagrodzenie;
    @XmlElement(required = true)
    protected String telefon;

    /**
     * Gets the value of the pesel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPesel() {
        return pesel;
    }

    /**
     * Sets the value of the pesel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPesel(String value) {
        this.pesel = value;
    }

    /**
     * Gets the value of the imie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImie() {
        return imie;
    }

    /**
     * Sets the value of the imie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImie(String value) {
        this.imie = value;
    }

    /**
     * Gets the value of the nazwisko property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwisko() {
        return nazwisko;
    }

    /**
     * Sets the value of the nazwisko property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwisko(String value) {
        this.nazwisko = value;
    }

    /**
     * Gets the value of the stanowisko property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStanowisko() {
        return stanowisko;
    }

    /**
     * Sets the value of the stanowisko property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStanowisko(String value) {
        this.stanowisko = value;
    }

    /**
     * Gets the value of the wynagrodzenie property.
     * 
     */
    public double getWynagrodzenie() {
        return wynagrodzenie;
    }

    /**
     * Sets the value of the wynagrodzenie property.
     * 
     */
    public void setWynagrodzenie(double value) {
        this.wynagrodzenie = value;
    }

    /**
     * Gets the value of the telefon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefon() {
        return telefon;
    }

    /**
     * Sets the value of the telefon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefon(String value) {
        this.telefon = value;
    }

}
