//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.23 at 07:59:17 AM CEST 
//


package ou.xjc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ou.xjc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Handlowiec_QNAME = new QName("", "Handlowiec");
    private final static QName _Dyrektor_QNAME = new QName("", "Dyrektor");
    private final static QName _Pracownik_QNAME = new QName("", "Pracownik");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ou.xjc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Handlowiec }
     * 
     */
    public Handlowiec createHandlowiec() {
        return new Handlowiec();
    }

    /**
     * Create an instance of {@link Dyrektor }
     * 
     */
    public Dyrektor createDyrektor() {
        return new Dyrektor();
    }

    /**
     * Create an instance of {@link Pracownik }
     * 
     */
    public Pracownik createPracownik() {
        return new Pracownik();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Handlowiec }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Handlowiec")
    public JAXBElement<Handlowiec> createHandlowiec(Handlowiec value) {
        return new JAXBElement<Handlowiec>(_Handlowiec_QNAME, Handlowiec.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Dyrektor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Dyrektor")
    public JAXBElement<Dyrektor> createDyrektor(Dyrektor value) {
        return new JAXBElement<Dyrektor>(_Dyrektor_QNAME, Dyrektor.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Pracownik }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Pracownik")
    public JAXBElement<Pracownik> createPracownik(Pracownik value) {
        return new JAXBElement<Pracownik>(_Pracownik_QNAME, Pracownik.class, null, value);
    }

}
